services:
  - type: web
    name: globeweather
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
